# Generated by Django 4.1.5 on 2023-01-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_apps', '0003_customer_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
    ]
