# Generated by Django 4.1.5 on 2023-01-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_apps', '0004_auto_20230116_1639'),
    ]

    operations = [
    ]
