# Generated by Django 4.1.5 on 2023-01-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_apps', '0005_auto_20230116_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
