# Generated by Django 4.1.5 on 2023-01-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_apps', '0006_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
