# Generated by Django 4.1.5 on 2023-01-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_apps', '0007_alter_customer_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='ecommerce_a_last_na_47f7c3_idx',
            old_name='store_custo_last_na_2e448d_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='ecommerce_apps_customer',
        ),
    ]
