# Generated by Django 4.1.5 on 2023-01-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_apps', '0008_rename_store_custo_last_na_2e448d_idx_ecommerce_a_last_na_47f7c3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='ecommerce_a_last_na_47f7c3_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
